### ISSUE TITLE
Responsive audio

### ISSUE THREAD

**Issue by jarrodu** [battermann/Luigi#5]
- Playback on mobile phones in a resource efficient way
- Maybe rely on Tone.js synth or something like this

**Comment by battermann** [comment]
Playback of the sequence seems to work. `onMouseDown` etc. does not seem to work well.

So for mobile, let's check if we can play back a sequence using tone.js synthesisers, to avoid loading the samples on startup.

And disable `onMouseDown` / `Up` events.

**Comment by battermann** [comment]
We could detect device type by using the elm style elements library (which I would like to use anyway for styling).
